# syntax=docker/dockerfile:1

FROM python:3.11-slim-bullseye

ENV PYTHONPATH "${PYTHONPATH}:."

WORKDIR /app/frontend

RUN apt update && apt install -y libmariadb-dev gcc && \
    rm -rf /var/cache/apt
COPY requirements.txt .    
RUN pip3 install -r requirements.txt

COPY . .

CMD python3 webapp/app.py
