# syntax=docker/dockerfile:1

FROM python:3.11-slim-bullseye

ENV PYTHONPATH "${PYTHONPATH}:."

WORKDIR /app/backend
COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

CMD python3 api/app.py
